# Generated by Django 5.1.5 on 2025-02-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_cep_alter_perfil_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
